# hugo.toml
baseURL = 'https://cloudhouse-org.github.io/'
languageCode = 'zh-cn'
title = 'CloudHouse Blog'

[params]
  author = "molqzone"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
    disable = false
