# hugo.toml
baseURL = 'https://cloudhouse-org.github.io/'
languageCode = 'zh-cn'
title = 'CloudHouse Blog'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
    disable = false
