# hugo.toml
baseURL = 'https://cloudhouse-org.github.io/'
languageCode = 'zh-cn'
title = '大云屋众创空间'

# Sitemap configuration
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  author = "molqzone"

  # Bing Webmaster Tools verification
  bingSiteAuth = "BingSiteAuth.xml"

  [params.math]
    enable = true

  # Custom head for MathJax
  [params.customJS]
    mathJax = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"
    disable = false
